[project]
name = "hello-world"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "typer-cli>=0.17.4",
]

[project.scripts]
hw = "hello_world.main:app"
