[project]
name = "hello-world-kannada"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.entry-points.hello_world]
kannada = "hello_world_kannada.main:KannadaLanguage"